### ISSUE TITLE
Different color for placeholder text

### ISSUE THREAD

**Issue by ritz078** [sohobloo/react-native-modal-dropdown#101]
That will be a great addition. Native components have that.

**Comment by sohobloo** [comment]
use it as a wrapper and render button yourself can achieve this goal at present.

**Comment by BrendanBerkley** [comment]
To clarify for anyone else searching:

You can use `<ModalDropdown>` as a component or as a wrapper/container, as the readme notes. If you do the latter, the contents inside of the wrapper will serve as the button, apparently overriding the `defaultValue` prop you can pass into ModalDropdown.
