### ISSUE TITLE
adds an icon in the dropdown?

### ISSUE THREAD

**Issue by dewabagasql** [sohobloo/react-native-modal-dropdown#108]
because if i pass the default value with an image, it gives me a warning that the defaultvalue should be string..

**Comment by mkpietrzyk** [comment]
What are you trying to achieve? Maybe we have similar problem.

**Comment by mkpietrzyk** [comment]
I am trying to achieve something like below 

I am able to add the icon near the mainTitle, but I don't know how to add the icon next to the selected row of dropdown... and this little 'edgy' triangle on top. I mean the latter is not that important but the 'check' icon next to the selected row/item would be perfect 

<img width="133" alt="zrzut ekranu 2017-11-22 o 15 07 59" src="https://user-images.githubusercontent.com/23457146/33131588-4bbb4a72-cf97-11e7-849b-9c1f9bde99a8.png">

**Comment by sohobloo** [comment]
@dewabagasql user this component as a wrapper and render the button yourself can solve the problem.

@mkpietrzyk use `renderRow` to solve your first problem.
the second one is a little complex
