### ISSUE TITLE
Disable scrolling when there are less items

### ISSUE THREAD

**Issue by Dineshchitta** [sohobloo/react-native-modal-dropdown#112]
I want to disable scrolling when there are below 5 items. Is it supported ?

**Comment by tehwayne** [comment]
There was supposed to be a way to disable scroll (see https://github.com/sohobloo/react-native-modal-dropdown/pull/35) but looks like it doesn't work anymore

**Comment by mchen37** [comment]
It is working for me. I have only 2 items in my list so far and it was scrolling before. I added
`scrollEnabled={false}` in my ModalDropdown props and it is no longer scrolling. I am using an iPad with iOS 11 and Expo if that makes a difference.
