### ISSUE TITLE
Dropdown displays at the top when there is not enough space at the bottom

### ISSUE THREAD

**Issue by kirakik** [sohobloo/react-native-modal-dropdown#114]
Hello,

I am getting an issue witgh the dropdown displaying at the top of the button when there is not enoug space at the bottom. I understand that this may be a feature and not a bug, but there should at least be a way to turn it off if not wanted.

![screen shot 2017-12-04 at 5 07 37 pm](https://user-images.githubusercontent.com/17203119/33578828-cd7c42be-d915-11e7-893b-ae0420365de9.png)

Thank you

**Comment by sohobloo** [comment]
Yeah... it's a feature.
You can use `adjustFrame` to change the position.
