### ISSUE TITLE
dropdown style

### ISSUE THREAD

**Issue by JayKurniawan** [sohobloo/react-native-modal-dropdown#115]
Hi, I'm literally new in React Native.
I'm a bit confuse how to use the `style` props. 
I don't know what are the possible values I can use to customize my dropdown.
Any help will be appreciated.

**Comment by sohobloo** [comment]
style: Change the style of the button (basic mode) / container (wrapper mode).
textStyle: Change the style of text of the button. Invalid in wrapper mode.
dropdownStyle: Change the style of dropdown container.

**Comment by Dror-Bar** [comment]
How to change the dropdownStyle backgroundColor ?

**Comment by Torebabe** [comment]
I want to change the dropdownStyle backgroundColor too (android).
it doesn't work.
But i cant see the backgroundColor when i  set a bigger height value.
it's behind the orignal content but not change the backgroundColor.

**Comment by Torebabe** [comment]
@Dror-Bar 
I checked the source code，we need to setting the backgroundColor of dropdownTextStyle.

**Comment by Dror-Bar** [comment]
@Torebabe 
Nothing like checking the source code. It seems weird that it works like that, but it works. Thanks a lot for the solution.
