### ISSUE TITLE
How to reset dropdown index?

### ISSUE THREAD

**Issue by nikasvan** [sohobloo/react-native-modal-dropdown#116]
Hi there, 

How can I reset Dropdown index? I would like to reset dropdown when component is receiving props `componentWillReceiveProps`. Tried `defaultIndex ={-1}` but I guess it works only only when component it mounted.  Is there any prop available for that?

**Comment by nikasvan** [comment]
Any improvement on this?

**Comment by nikasvan** [comment]
Just figured it out `ModalDropdown` Component should have a ref prop for example `ref={ (ref) => this.lookaheadFilter = ref ` and where-ever you would like to reset it the dropdown you just add this `this.lookaheadFilter.select(-1);`

**Comment by sohobloo** [comment]
Yeah you get it!
