### ISSUE TITLE
Full width dropdown

### ISSUE THREAD

**Issue by thedjinn** [sohobloo/react-native-modal-dropdown#12]
Hi! Thanks for making this component! I have a suggestion: it would be nice to have an option to allow the dropdown menu to take the entire width of the button (or wrapper in my case). This looks a lot nicer on wrappers that use the full width of the screen.

**Comment by sohobloo** [comment]
@thedjinn 
Thanks for your suggestion.
I think you can define the width by given a style to `dropdownStyle` property like this:
 [code 1](https://github.com/sohobloo/react-native-modal-dropdown/blob/v0.3.2/example/index.js#L55) [code 2](https://github.com/sohobloo/react-native-modal-dropdown/blob/v0.3.2/example/index.js#L219)
Have a try.
 :-)

**Comment by sohobloo** [comment]
@thedjinn 
Any problem with my reply?
If it solves your question please let me know then I can close it. Thanks!
 :-)

**Comment by aelallam** [comment]
@sohobloo  hello, I was thinking more of a width = null so that the dropdown will take the width of the entire screen. I cannot set a specific width because I do not the the width of different screens of phones. How can I do this ?

**Comment by sohobloo** [comment]
@aelallam
Dimension.get('window').width
