### ISSUE TITLE
严重bug，修改props.defaultValue, props.defaultIndex，不刷新

### ISSUE THREAD

**Issue by 13980519619** [sohobloo/react-native-modal-dropdown#125]
1.直接调用改组件，传defaultValue，defaultIndex，正确
2.直接setState主组件，传不同的defaultValue，defaultIndex，正确，因为componentWillReceiveProps函数里面的selectedIndex为-1.
3.问题(来了)：直接setState主组件，传不同的defaultValue，defaultIndex，此时选择一个数据，修改了selectedIndex，selectedIndex值大于0，此时的defaultValue，defaultIndex没有效果。

源码：
componentWillReceiveProps(nextProps) {
    if (selectedIndex < 0) {
      selectedIndex = nextProps.defaultIndex;
      if (selectedIndex < 0) {
        buttonText = nextProps.defaultValue;
      }
    }
  }
不知是否可以修改为：默认传-1时，显示之前的defaultValue
componentWillReceiveProps(nextProps) {
      selectedIndex = nextProps.defaultIndex;
      if (selectedIndex < 0) {
        buttonText = nextProps.defaultValue;
      }
    }
  }

**Comment by sohobloo** [comment]
> 3.问题(来了)：直接setState主组件，传不同的defaultValue，defaultIndex，此时选择一个数据，修改了selectedIndex，selectedIndex值大于0，此时的defaultValue，defaultIndex没有效果。

既然你选择了一个数据，此时不是应该显示你选的数据吗？等你调用select(-1)时上边的代码仍然会显示新的defaultValue呀

**Comment by 13980519619** [comment]
我的我问题是这样的：当我选择了数据后，selectedIndex>0了，之后，我因产品需求，手动设置一个默认值，这个默认值没有效果。

**Comment by 13980519619** [comment]
i already fixed, i set once select(-1),

**Comment by sohobloo** [comment]
正确用法是这样的：
`defaultValue`和`defaultIndex`只影响控件首次渲染时的默认显示和默认勾选
如果在选择了选项之后想要再显示回defaultValue需要调用select(-1)

如果有问题可以告知，这个issue关了
