### ISSUE TITLE
renderButtonText does not work

### ISSUE THREAD

**Issue by Mexxerio** [sohobloo/react-native-modal-dropdown#127]
The newly added `renderButtonText` property does not work. The function gets called after an option is selected, but it doesn't correctly set the button text. It still shows `[object Object]`.

**Comment by IvanIvaschenko** [comment]
I have same problem.

**Comment by IvanIvaschenko** [comment]
@Mexxerio Check your package.json. And change "react-native-modal-dropdown": "^0.5.0" to "^0.6.0".

**Comment by Mexxerio** [comment]
@IvanIvaschenko It already is on `^0.6.0`. I specifically updated it to use that new feature.

**Comment by IvanIvaschenko** [comment]
@Mexxerio find the module in node_modules. Open ModalDropdown and look on line 361 you should  see this string buttonText: renderButtonText && renderButtonText(rowData) || rowData.toString(). If no try to restart packager.

**Comment by Mexxerio** [comment]
@IvanIvaschenko It's there.

**Comment by IvanIvaschenko** [comment]
@Mexxerio share your code.

**Comment by jorgemarrero** [comment]
Hi, I have the same or similar problem.
renderButtonText only runs after I select a value
This is my code: 

	renderInput(props) {
        console.log(props);
		// this runs after select a value from the dropdown and it return the value selected
    }

    render() {
        return (
            <View>
                <ModalDropdown
                    options={['Sunday',
                                'Monday',
                                'Tuesday',
                                'Wednesday',
                                'Thursday',
                                'Friday',
                                'Saturday',
                    ]}
                    defaultValue='Monday'
                    renderButtonText={this.renderInput}
                />
            </View>  
        );
    }

**Comment by atul-forbinary** [comment]
is this library work both ios and android , i am still getting [object object ]

**Comment by mrkirchner** [comment]
I am also getting this issue as well.    Here is a snippet of my code I continue to get [object object] and i double checked that im on version ^0.6.0.

`   const renderPrompt = (rowData) => {
      return `${rowData.name}`;
    };

<ModalDropdown ref={el => this.dropdown = el}
                       options={this.props.options}
                       renderButtonText={renderPrompt}
                       renderRow={rowRender}
                       onSelect={this.props.selectChangeHandler}/>
   
`

**Comment by IvanIvaschenko** [comment]
@atul-forbinary @mrkirchner You can use dirty hack. 
const Languages = [
  { value: 'English', source: require('../../../assets/gb.png'), locale: 'en' },
  { value: 'Espanol', source: require('../../../assets/es.png'), locale: 'es' },
  {
    value: 'Francais',
    source: require('../../../assets/fr.png'),
    locale: 'fr'
  },
  {
    value: 'Portuguese',
    source: require('../../../assets/pt.png'),
    locale: 'pt'
  },
  { value: 'Deutsch', source: require('../../../assets/de.png'), locale: 'de' },
  { value: 'Italiano', source: require('../../../assets/it.png'), locale: 'it' }
]

<ModalDropdown
          options={Languages.map(item => item.value)}
          textStyle={[styles.text, styles.regularText]}
          style={styles.dropdown}
          onSelect={(indx, value) => this.onSelect(value, indx)}
          dropdownTextStyle={[styles.text, styles.dropdownText]}
          dropdownStyle={styles.dropdownStyle}
          defaultValue={this.state.lang}
          renderRow={this.renderRow.bind(this)}
        />

onSelect = async (value, indx) => {
    let Lang = Languages[indx]
   ...
  }

**Comment by mrkirchner** [comment]
@IvanIvaschenko Not sure what your trying to show here.  Anytime i try to setState or call a props.function in my selectHandler it will not work.  

@sohobloo Any suggestions on whats going on or is it a bug?  Doing a quick look at your js it seems like renderButtonText is only being used onPress  does it also need to happen on select(idx) or componentWillReceiveProps?

**Comment by mrkirchner** [comment]
Opened an MR https://github.com/sohobloo/react-native-modal-dropdown/pull/131 not sure if that is best way to fix things.  Still learning react ...

**Comment by sohobloo** [comment]
This issue has been fixed. Please update to v0.6.1

Sorry, my fault and thanks to @swb2016(#128)
and also thanks to @mrkirchner

**Comment by Culzean** [comment]
I am also still finding this issue, I have version 0.6.1

**Comment by brascene** [comment]
@sohobloo same here, 0.6.1 version and still hitting the [object] thing, why is this so tough to get working?
