### ISSUE TITLE
onSelect question

### ISSUE THREAD

**Issue by ajonno** [sohobloo/react-native-modal-dropdown#13]
thanks for this component!

is it possible to change the background color of a cell when a user taps ? i wasnt sure which property / style to tweak to change that.

**Comment by sohobloo** [comment]
@ajonno 
I've already considered your situation. Please see this issue and wait for my release v0.4.0, and then you can render your option rows with `renderRow` function and use `TouchableHighlight` component with the `overlayColor` you like.

By the way, at present, you can still render your rows without wrapping any `Touchable` component, and give a `backgroundColor` to the row component. This will workaround one small mistake made by my default `renderRow` function which causes the black highlight when user tap the row (If you are facing this situation which lead to this topic.)

Hope you can understand my poor Chinglish. :-)

**Comment by ajonno** [comment]
hey thanks for quick reply. your english is perfect (wish i could speak mandarin! :-).  im in middle of big project at moment so not sure ill have time today to test, but am happy to wait for 0.4.0.  when do you think it will be ready to release ?

**Comment by sohobloo** [comment]
@ajonno 
> when do you think it will be ready to release ?
I have one more feature to complete before v0.4.0 formal release. I wish I can finish it on this Saturday.
But, I can draft a v0.4.0-rc1 for you.

**Comment by ajonno** [comment]
great thanks! its ok i can wait until next week. 

one quick related question - lets say i have a drop down list where the choices are "Year 1", "Year 2", "Year 3" and the user taps on "Year 2".  However I want to display the selected value, as "2". 

I can see the onSelected method but wasn't sure how to update that displayed (chosen) value field ?

**Comment by ajonno** [comment]
oh and one more quick question - will the update mean that the ENTIRE row can now recognise and capture a tap event, since it will be using TouchableHighlight etc ?

**Comment by sohobloo** [comment]
@ajonno 
Here are the sample codes: 
[Line 82](https://github.com/sohobloo/react-native-modal-dropdown/blob/v0.3.2/example/index.js#L82) gives a `defaultValue` maintained by the state to the dropdown.
[Line 144](https://github.com/sohobloo/react-native-modal-dropdown/blob/v0.3.2/example/index.js#L144) You can change the state of `defaultValue` at the right time. Considering your requirement, I think it is `onSelect`.

**Comment by sohobloo** [comment]
> oh and one more quick question - will the update mean that the ENTIRE row can now recognise and capture a tap event, since it will be using TouchableHighlight etc ?

I think the entire row can recognise and capture a tap event since my very first release. Sorry I do not understand what is your problem.

**Comment by ajonno** [comment]
here's quick snap of what i was referring to. 
![2016-12-02_15-02-31](https://cloud.githubusercontent.com/assets/3005269/20822662/b20086d0-b8a0-11e6-8b50-a5aae4f640c7.gif)

**Comment by sohobloo** [comment]
@ajonno 
Check your react-native version whether it's >= 0.36.0
If so, try update dropdown component to v0.4.0

**Comment by ajonno** [comment]
yes its 0.37. ok ill give that a try thanks

**Comment by ajonno** [comment]
sorry for delay im back to this now. 
ive updated to 0.4.0 via npm

re-ran app and the drop down has the same behavior? i do feel like im missing something obvious but to help, here is the JSX block im using for tests:
```
 <ModalDropdown
          options={['1', '2','3','4','5','6' ]}
          renderRow={this._dropdown_renderRow.bind(this)}
          style={{
             height: 30,
             paddingBottom: 8,
          }}
          textStyle={{
              opacity: 0.5,
              fontSize: 17,
              fontFamily: 'Montserrat-Medium'
           }}
           defaultValue={this.state.dropdown_4_defaultValue}
           onDropdownWillHide={this._dropdown_4_willHide.bind(this)}
           dropdownStyle={{
               //backgroundColor: 'red',
               //color: '#9B9B9B',
               width: 100,
               height: 240,
               alignItems: 'center',
               justifyContent: 'center',
            }}
            onSelect={(idx, value) =>  this.setState({selectedYear: value})}
       >
</ModalDropdown>
```
renderRow() method:
```
_dropdown_renderRow(rowData, rowID, highlighted) {

      return (
            <View style={[styles.dropdown_2_row]}>
             <Text style={[styles.dropdown_2_row_text, highlighted && {paddingLeft: 0, color: 'blue'}]}>
                {rowData}
             </Text>
            </View>
      );
   }
```
and styles:
```
const styles = StyleSheet.create({
   container: {
      flex: 1,
      backgroundColor: '#EEF4FC',
      paddingTop: 10
   },
   dropdown_2_row: {
    flex: 1,
    flexDirection: 'row',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center'
  },
  dropdown_2_row_text: {
//     backgroundColor: 'green',
    marginHorizontal: 4,
    fontSize: 16,
    color: '#7FA5B3',
    textAlignVertical: 'center',
  },
});
```

**Comment by ajonno** [comment]
just to let you know all good, thanks again
