### ISSUE TITLE
Dropdown menu not showing properly while ModalDropdown in bottom part of screen

### ISSUE THREAD

**Issue by maxhis** [sohobloo/react-native-modal-dropdown#130]
There are two `ModalDropdown`s in my screen, the first on work fine and the second show the drop-down menu just under the status bar(see the attached image).

![image](https://user-images.githubusercontent.com/1464097/35552434-ce95f13c-05ce-11e8-951b-8bed49554174.png)

Here is my code snippet:

```js
<ModalDropdown
  defaultValue='请选择'
  {...this.props }
  style={styles.dropdownButton}
  textStyle={styles.item}
  dropdownStyle={styles.dropdownContainer}
  dropdownTextStyle={styles.item}
/>

const styles = StyleSheet.create({
  dropdownButton: {
    flex: 1,
    marginLeft: 5,
  },
  dropdownContainer: {
    height: 'auto',
    flexDirection: 'row',
  },
  item: {
    fontSize: 18,
    color: AppColors.textColor,
  },
});
```

When I comment out the line `height: 'auto',`, the drop-down menu will show in the proper location but show empty row if less than 4 items.

**Comment by dinhtho** [comment]
I have same issue and I think this is the problem. Take a look in ModalDropdown component.
dropdownHeight ='auto' so bottomSpace >= dropdownHeight cannot true.
you should use adjustFrame to change position of dropdown list
let showInBottom = bottomSpace >= dropdownHeight || bottomSpace >= this._buttonFrame.y;

**Comment by sohobloo** [comment]
@maxhis 
if you need to set the dropdown height dynamically, my suggestion is remove `height: 'auto'` to avoid incorrect position calculate and use `adjustFrame` to change the `height` like this:

```jsx
<ModalDropdown
  defaultValue='请选择'
  {...this.props }
  style={styles.dropdownButton}
  textStyle={styles.item}
  dropdownStyle={styles.dropdownContainer}
  dropdownTextStyle={styles.item}
  adjustFrame={(style) => {
    style.height = [your height value];
    return style;
  }}
/>
```

**Comment by sohobloo** [comment]
There were no 'auto' or percentage width/height styles when I developed this component. Position calculate was based on numeric styles. 
So It's hard to compatible with these new features in react-native or I have to redesign the core position calculate functions.

**Comment by maxhis** [comment]
@sohobloo Thanks, I get it work on your suggestion.

**Comment by Quem** [comment]
Hi there,
I've having this same problem but using the solution from @sohobloo didn't solve it.

I'm using 
`
adjustFrame={(style) => {
 const frameHeight = (40*data.length); // 40 = img size + margin
 
 style.height = frameHeight;
 
 return style;
}}
`
In the code above there are cases where the height is only 40, still it calculated the height remaining to the bottom of the page with the default height value instead of the new one. So even if the value if more than enough to fit it will still be pushed above the dropdown.

**Comment by sohobloo** [comment]
3 am bothering by insonia.

@Quem
Try set this height in `dropdownStyle` and it will be available in position calculation. `adjustFrame` is used after that calculation.

**Comment by csgonutty** [comment]
Firstly thanks for a fantastic component, it's really helped me. I've used your method above @sohobloo but it appears that my dropdown modal doesn't adjust it's position when it runs of the screen. I set my height to 400 via the adjustFrame function

Is there any prop that I can pass that would allow me to position the modal in the middle of the screen.

**Comment by sohobloo** [comment]
@csgonutty 
Did you return the style after you set the height of it?

**Comment by maxhis** [comment]
Here is my final workaround, for someone facing the same problem:

```js
const optionsCount = this.props.options.length;

<ModalDropdown
    {...this.props }
    style={styles.dropdownButton}
    textStyle={styles.item}
    dropdownStyle={[...styles.dropdownContainer, {height: optionsCount > 4 ? 'auto' : -1}]}
    dropdownTextStyle={styles.item}
    adjustFrame={(style) => {
        style.height = optionsCount > 4 ? style.height : -1;
        return style;
    }}
/>
```

**Comment by Fox-3394** [comment]
Many thank @sohobloo @maxhis
