### ISSUE TITLE
Unable to select or view dropdown last elements when the list is long?

### ISSUE THREAD

**Issue by faisalazeez** [sohobloo/react-native-modal-dropdown#134]
I am unable to select the last element since the list is long. The scrolling won't help me to select the last elements.

**Comment by faisalazeez** [comment]
I have added height as auto for the dropdownStyle props

**Comment by faisalazeez** [comment]
And also the scrolling is not working for Android

**Comment by sohobloo** [comment]
height: 'auto' will make the dropdown stretch to contain all of the option rows, so there is no scrolling , and if too long, some of items will display off the screen.

**Comment by FanJfly** [comment]
I fixed this question by setting like this: {height: 'auto', maxHeight: 500}

> And also the scrolling is not working for Android
