### ISSUE TITLE
Add onCancel functionally please!

### ISSUE THREAD

**Issue by jacm80** [sohobloo/react-native-modal-dropdown#135]
Thanks for shared the component!

This suggestion for you!

Add  this.props.onCancel();

onPressCancel() {
    this.hide();
    this.props.onCancel();
  }

this allow

<SimplePicker 
          confirmText={'Confirmar'} 
          options={this.props.options} 
          ref={'picker'}
          cancelText={'Cancelar'}
          initialOptionIndex={0}
          onSubmit={ this.onChainPress.bind(this) }
          onCancel={ this._initialState.bind(this) }       => chain action when the user cancel the select list
 />

**Comment by sohobloo** [comment]
@jacm80 
There is a `onDropdownWillHide` function.
