### ISSUE TITLE
defaultIndex property does not work

### ISSUE THREAD

**Issue by marcin-solvenet** [sohobloo/react-native-modal-dropdown#138]
Hi,

Thanks for awesome and useful library!.

O noticed that probably defaultIndex is ignored, any value I set 0,1,3 always get default text 'Please select...' - Tested on iOS

Please have a look when you have time

Thanks
Marcin

<ModalDropdown options={[strings.veryGoodCondition, strings.goodCondition, strings.sufficientCondition, strings.badCondition]}
                        defaultIndex={0}
                        onSelect={(idx, value) => {
                          this.props.updateIssueStatus(item.id, this.conditionStatusToIndex[idx], value);
                        }}
                        style={controlStyles.dropDownContainerStyle}
                        textStyle={{}}
                        dropdownStyle={controlStyles.dropDownStyle}
                        dropdownTextStyle={controlStyles.dropDownItemTextStyle}
                        textStyle={controlStyles.dropDownItemTextStyle}/>

**Comment by sohobloo** [comment]
`defaultIndex` only change the highlight of the dropdown row, you have to give a `defaultValue` to change the init text.
