### ISSUE TITLE
How can i keep the defaultValue, after the selection ?

### ISSUE THREAD

**Issue by MERTKIRKALI** [sohobloo/react-native-modal-dropdown#148]
Hi,

I want to keep my defaultValue after selection. But my code doesn't work.

`  style={styles.counter} options={['Şikayet Et']}
            defaultIndex={-1}
            defaultValue={this.state.dropdown_defaultValue}
            onSelect={(idx, value) => this.sikayetClick(idx, value)}
            textStyle={{ color: 'darkred', fontSize: 20 }}
            dropdownStyle={{ height: 48 }}
            dropdownTextStyle={{ fontSize: 20, color: 'black' }}
            onDropdownWillHide={this.dropdownWillHide.bind(this)}`

`dropdownWillHide() {
    this.setState({
      dropdown_defaultValue: ...,
    });
  }`

**Comment by sohobloo** [comment]
call `this.refs.dropdown.select(-1)` will reset to display the `defaultValue `
