### ISSUE TITLE
How to change the color of the data row when tap on it?

### ISSUE THREAD

**Issue by tonnth** [sohobloo/react-native-modal-dropdown#149]
Sorry for my English.
I want to change the color of data row (animation color when tapping on data row) but I don't know how to do that

**Comment by sohobloo** [comment]
use `renderRow` prop and `TouchableHighlight` component.

```jsx
renderRow = (option, index, isSelected) => {
  return (
    <TouchableHighlight underlayColor="...">
      ...
    </TouchableHighlight>
  )
};
```

**Comment by tonnth** [comment]
Thank you @sohobloo
