### ISSUE TITLE
Dropdown display on top of the screen

### ISSUE THREAD

**Issue by guidoprinc** [sohobloo/react-native-modal-dropdown#151]
Hi there!

I was using the dropdown and realized that when there isn't enough space in the bottom of the screen, the dropdown will appear on top of the device. ¿Is there a way to always show the dropdown on the bottom of its component?

Here is a screenshot of how it looks like:

![screen shot 2018-03-12 at 10 41 19 am](https://user-images.githubusercontent.com/28304582/37286844-ed2e7fc8-25e1-11e8-864d-261cf63d8bef.png)

**Comment by sohobloo** [comment]
Did you set an `auto` height of the dropdown style?

**Comment by guidoprinc** [comment]
i did. I deleted it and solved the issue. Thanks @sohobloo!
