### ISSUE TITLE
dropdown/app freezes upon selection

### ISSUE THREAD

**Issue by barron9** [sohobloo/react-native-modal-dropdown#162]
Hi

I am using this simple code, but dropdown freezes itself after i tap an option

```
<ModalDropdown options={['option 1', 'option 2']}
ref={ (ref) => this.lookaheadFilter = ref }
onSelect={ (idx, value) =>alert(idx) }
/>
```

if i use alert function or custom function it doesnt matter it stuck

**Comment by wmfarooqi05** [comment]
This can be resolved by binding the calling function

**Comment by barron9** [comment]
can you explain it in a code

**Comment by wmfarooqi05** [comment]
This line was causing problem

onSelect={(idx, value) => this.onOptionSelect(idx, value)}

After binding it started working

onSelect={(idx, value) => this.onOptionSelect.bind(idx, value)}

**Comment by barron9** [comment]
yes
