### ISSUE TITLE
Array of objects as Options...

### ISSUE THREAD

**Issue by sagark1510** [sohobloo/react-native-modal-dropdown#19]
Hi, plugin works well and I have tried providing array of objects to options using `renderRow` method it shows dropdown but when I see console it throws error of `Invalid prop options[0] of type object supplied to ModalDropdown, expected string.`.

Can it be possible in current version or only string options are supported?

**Comment by sohobloo** [comment]
Only string options are supported so I can display it on the button when the option is selected.
