### ISSUE TITLE
我就想问中国人为什么要用英语注释

### ISSUE THREAD

**Issue by jameshuimin** [sohobloo/react-native-modal-dropdown#192]
哈哈哈哈

**Comment by t880216t** [comment]
We speak  this common language，Because  of in order to let more people understand the progress of the problem.
Garbage is applied to everywhere， this isn't an exclusively Chinese phenomenon.
I just want to discuss technology here, But I feel ashamed to see you.

**Comment by jameshuimin** [comment]
It just kidding，programmers to laugh at themselves.
