### ISSUE TITLE
First click the button ,but the dropdown menu does not on right space 。

### ISSUE THREAD

**Issue by chen236310** [sohobloo/react-native-modal-dropdown#2]
when I used navigator push to detail, I click the button ,it show that the was not  on the right place ,but the after second click,it was right. I debug it ,it show that the first click I got this._buttonFrame was wrong.

**Comment by sohobloo** [comment]
@chen236310 Thanks a lot. I'm working on it.

**Comment by sohobloo** [comment]
I'd like to find a way to update the position when the layout of the button / trigger related to the screen changed within the component code itself.
Anyone any suggestion are welcome!

**Comment by sohobloo** [comment]
@chen236310 
Good news. Try v0.3.0 and give me a feedback if your problem solved.

**Comment by chen236310** [comment]
Thank you for your advise,I think that  can you get update the position twice  within the component code itself .
