### ISSUE TITLE
Unhandled JS Exception: "flexGrow" is not a valid style property

### ISSUE THREAD

**Issue by skyFi** [sohobloo/react-native-modal-dropdown#20]
![image](https://cloud.githubusercontent.com/assets/12740180/21071042/6f813a72-becf-11e6-893e-6bc12d14c179.png)

**Comment by sohobloo** [comment]
@skyFi

**Comment by sohobloo** [comment]
@skyFi 
This style property 0.34.1 became a part of RN until v0.34.1

You can update your RN or just use a lower version (v0.3.2) of my component.

**Comment by skyFi** [comment]
thx
