### ISSUE TITLE
dropdown panel over screen's height can't scroll

### ISSUE THREAD

**Issue by FanJfly** [sohobloo/react-native-modal-dropdown#203]
when I add 20 data to dropdown panel, I set dropdown style: {height: 'auto'},but  the dropdown height is over screen height , it can't scroll, i cant's get data on bottom
like this: 
![image](https://user-images.githubusercontent.com/13930018/48249891-609c7280-e437-11e8-8b6e-cc869f655403.png)

**Comment by SuperBesse** [comment]
I have the Same problem

**Comment by SuperBesse** [comment]
Thnaks @FanJfly for the answer. I use it to fix my issue.
