### ISSUE TITLE
RN v0.36 ios 当点击按钮调用onSelect方法后就会卡死

### ISSUE THREAD

**Issue by Wisonan** [sohobloo/react-native-modal-dropdown#22]
如题，
程序卡死，dropdown列表也不没隐藏
代码：
<ModalDropdown
  options={['option1', 'option2']}
  onSelect={(idx, value) => { alert('index=' + idx) }}>
  <View> ... </View>
</ModalDropdown>

**Comment by sohobloo** [comment]
看上起像是RN的一个Bug，请把alert去掉。。。。

**Comment by Wisonan** [comment]
解决了，谢谢！

**Comment by sohobloo** [comment]
Fixed in v0.4.1
Temporary comment calling `alert` in demo app.
