### ISSUE TITLE
如何让dropdown撑满整个屏幕？

### ISSUE THREAD

**Issue by anhuiliujun** [sohobloo/react-native-modal-dropdown#25]
我的需求
* dropdown有个遮罩层，撑满屏幕，一直到屏幕底部
* dropdown有个高度，这个高度不会到屏幕底部

我发现目前dropdown只能设置一个高度，无法实现我所说的需求，

**Comment by sohobloo** [comment]
dropdown目前有遮罩（modal），只是我设了透明背景，暂时不支持自定义
dropdown本身的位置是依据按钮位置来显示的
如果你对这样的显示方式不太满意，可以使用`adjustFrame`属性对其中的高宽、位置参数进行调整再作为返回值即可
