### ISSUE TITLE
options最多10个，超过10个后，一选择就出错。

### ISSUE THREAD

**Issue by pengfeiyan** [sohobloo/react-native-modal-dropdown#27]
把您的例子中修改如下，其他不动，可以再现。
const DEMO_OPTIONS_1 = ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', 'option 6', 'option 7', 'option 8', 'option 9','option10','aaaaaa'];

错误信息如下
View was rendered with explicitly set width/height but with a 0 flexBasis. (This might be fixed by changing flx: to FlexGrow:)
View:<RCTShadowWiew: 0x6080001bbc80; viewName:RCTView; reactTag:72;frame:{{0,0},{146,40}}>

react-native:0.39.2
虚拟机上跑的
![错误信息截图](https://cloud.githubusercontent.com/assets/24911989/21637584/ef526c32-d2aa-11e6-8a5c-1fa0b659a7cb.png)

**Comment by pengfeiyan** [comment]
![出错画面](https://cloud.githubusercontent.com/assets/24911989/21637565/cd3b82aa-d2aa-11e6-9850-255942d2d64a.png)

**Comment by sohobloo** [comment]
I create a clear copy same as your env but still can't reproduce it.
Sorry but I'll try more later.

**Comment by pengfeiyan** [comment]
画面初期化可以正常出来，之后点击选择下拉，下拉出来之后瞬间立马就红色错误

**Comment by pengfeiyan** [comment]
前面是IOS的，今天又在安卓上仅代码<ModalDropdown options={['option 1', 'option 2', 'option 3', 'option 4', 'option5', 'option6', 'option7', 'option8', 'option9', 'option10','11','12','13','14','15','16']}/>来测试。
![image](https://cloud.githubusercontent.com/assets/24911989/21792296/0c45aa18-d72c-11e6-972d-f4c5315476d3.png)

**Comment by pengfeiyan** [comment]
非常感谢您的修改。已经确认过了，IOS/ANDROID都OK了。
