### ISSUE TITLE
option里面的字体大小颜色应该怎么修改？

### ISSUE THREAD

**Issue by Swordce** [sohobloo/react-native-modal-dropdown#28]

**Comment by sohobloo** [comment]
你可以使用`renderRow`方法来定制option展示。

**Comment by Swordce** [comment]
可不可以将下拉出来的菜单改成这种样式呢，defaultStyle里面修改不了吧
![image](https://cloud.githubusercontent.com/assets/16829238/21841931/64be8324-d81f-11e6-9650-a93b1d85d3c6.png)

**Comment by sohobloo** [comment]
右上角的箭头样式暂时支持不了哦

**Comment by Swordce** [comment]
有没有办法在背景上放一个图片上去，原先的那个框设置成透明的

**Comment by sohobloo** [comment]
你可以尝试在`renderRow`里做这些，为每一行放一张背景图试试，这样可以做到第一行与其他行不同。
