### ISSUE TITLE
Disable option

### ISSUE THREAD

**Issue by brascene** [sohobloo/react-native-modal-dropdown#38]
Is there option to make one or more of options disabled for touch? In other words, if I click on specific option, I don't want it to be selected.

Thanks!

**Comment by sohobloo** [comment]
@brascene 
Yes, please see the example below.

```javascript
<ModalDropdown onSelect={this._onSelect}/>

_onSelect(value, idx) {
    if (someCondition) return false; // Prevent to be selected.
    return true; 
}
```
