### ISSUE TITLE
Array of objects as option

### ISSUE THREAD

**Issue by stoffern** [sohobloo/react-native-modal-dropdown#39]
Works fine when you set a renderRow function. 
But when you select a option, the selected data is set to [Object object].. it should use the renderRow function to extract the data to show.
Or a seperate function that is

**Comment by sohobloo** [comment]
Yes. I don't know the data structure of your array so you have to do the work on your own renderRow.

**Comment by stoffern** [comment]
it should implemented a function for the render of the current element.
As your example and docs provide information that points to Objects can be used.

**Comment by sohobloo** [comment]
I think it's the same for developers to just use `renderRow` to do it.
Or I missunderstand what you mean?

**Comment by Amila17** [comment]
Hi @sohobloo  firstly, thanks for the component. But I am facing the same issue as @stoffern. I have provided a function to generate the view required for renderRow. However, after the row is selected, the name displayed is `[object Object]`. This is the code I am using:

`<ModalDropdown 
            options={collection}
            renderRow={(row) => displayRow(row)}
            onSelect={...} />`

`const displayRow = (data) => {
    return (
        <TouchableHighlight>
            <View style={styles.row}>
                <Image source={{ uri: data.image}} style={styles.photo} />
                <Text style={styles.selectedFont}>{`${data.name} (${data.age})`}</Text>
            </View>
        </TouchableHighlight>
    )
}`

Do you see anything wrong here? Ignore the onSelect function.

**Comment by sohobloo** [comment]
@Amila17 @stoffern

**Comment by sohobloo** [comment]
As I mentioned in this commit 9f3bc087bdb5ad4748cb2e7030d144249a367c50
Be sure to render your own trigger or I don't know what text to display
on it.

**Comment by Amila17** [comment]
@sohobloo yeap, that makes sense now. For the moment I will use the workaround you have mentioned above. But I guess it would be better to specify a property like `modalDropDownName` when providing object array's as a source. This would make things cleaner.

Thanks for the response 👍

**Comment by itswaze** [comment]
@Amila17 can you show me how you solved this problem?

Im having the same problem with data fetched from json array. But I don't know how to render my own button and use it as wrapper. Im new to react native.

**Comment by kidolee** [comment]
我觉得他的意思就是用object类型的array作为数据放入  options里面不能使用，因为 没有类似 picker组建的 selectedValue 和 onvaluechange,   当用objectArray作为options，你选择某个选项上面只会显示{object,object} 不能正常显示 object的 key 或 value

**Comment by cliang0917** [comment]
我现在就碰到了这个问题~显示{object,object} 。看来得自己改下了。

**Comment by dengshasha** [comment]
传入对象的时候显示[object object]这个到底咋解决啊，一脸懵逼

**Comment by sohobloo** [comment]
https://github.com/sohobloo/react-native-modal-dropdown/issues/122#issuecomment-357132865
