### ISSUE TITLE
First touch don't show dropDown

### ISSUE THREAD

**Issue by julien-innovantic** [sohobloo/react-native-modal-dropdown#4]
Hi,
thanks for this helpful component :) But on first click, the list don't appear. I see the touch effect and on second touch, list appears correctly.
I use it for android, so i have no idea if this issue can be reproduced on IOS.

Have you an idea to fix it ?

thanks.

**Comment by sohobloo** [comment]
@julien-innovantic 
If you are using a navigator component, have a look at this issue #2 .  I gave a workaround solution below. Otherwise, I have to know what changes the parent container's layout after its init and then try to find a way to fix it or give you another similar solution.

Thanks.

**Comment by sohobloo** [comment]
@julien-innovantic 
Good news. Try v0.3.0 and give me a feedback if your problem solved.

**Comment by julien-innovantic** [comment]
@sohobloo: thanks, 0.3.0 fix my problem.
