### ISSUE TITLE
多个 dropdown 不能同时打开

### ISSUE THREAD

**Issue by moyuyc** [sohobloo/react-native-modal-dropdown#40]
```
componentDidMount() {
   this.refs.b.show();
   this.refs.a.show();
}
```

![image](https://cloud.githubusercontent.com/assets/13509258/23511173/40fbb764-ff97-11e6-8ffd-71ecbd2fd590.png)

**Comment by sohobloo** [comment]
一个dropdown对应一个modal
恐怕暂时无法支持多个同时显示
您需要的也许是picker类控件？
