### ISSUE TITLE
How to disable fade in animation?

### ISSUE THREAD

**Issue by ARMATAV** [sohobloo/react-native-modal-dropdown#44]
Hey @sohobloo - is there a way to disable the fade in animation and _instantly_ open the dropdown menu?

**Comment by sohobloo** [comment]
I'm sorry it's not configurable right now.

**Comment by sohobloo** [comment]
Try v0.4.2~~~

**Comment by ARMATAV** [comment]
Dude it's so much better now with animated=false, thanks so much for the addition man - I'll use this in production. Awesome!
