### ISSUE TITLE
Array of objects

### ISSUE THREAD

**Issue by itswaze** [sohobloo/react-native-modal-dropdown#47]
I know this is already an open issue, but I need help and nobody answered.

I have the same issue as #39, but I don't know how to render my own button and use it as a wrapper.
If someone could help me, would be great!

**Comment by sohobloo** [comment]
```
<ModalDropdown options={[{name: 'option_1'}, {name: option_2}]}
                             onSelect={(idx, value) => this.setState({selectedValue: value.name})}>
  <Text>{this.state.selectedValue}</Text>
</ModalDropdown>
```

Hope this is what you want.

**Comment by itswaze** [comment]
Hi @sohobloo and thanks for the help.
Thats exactly what I wanted, and its working just fine!

But I see that defaultValue is invalid in wrapper mode. And I need to show a defaultValue, how can i show a defaultValue this way?

**Comment by sohobloo** [comment]
YW, you can set the initial state of `selectedValue` in constructor.

```jsx
  constructor(props) {
    super(props);

    this.state = {
        selectedValue: 'Please select...'
    };
  }
```

**Comment by itswaze** [comment]
That's it! Thank you so much for the help. Keep up the good work!
