### ISSUE TITLE
Position is wrong when presented on iPad with Form Sheet presentation style

### ISSUE THREAD

**Issue by DrBeak1** [sohobloo/react-native-modal-dropdown#5]
Reproduce:
(1) Launch new view controller as form sheet.
(2) Tap drop down.

Expected:
- dropdown drops down at x,y (or just below) 'please select'.

Actual:
- drop down drops down at x,y of screen.

**Comment by sohobloo** [comment]
@DrBeak1 
It would be nice if you could provide an simplest demo which can reproduce this issue.
Thanks a lot for your feedback!

**Comment by DrBeak1** [comment]
sorry, don't have time to build a demo for you, but i can do next best thing. see below class and screenshot. This is all done as basic and simple as you can imagine. note that react is integrated into my obj-c project using steps [here](https://facebook.github.io/react-native/docs/integration-with-existing-apps.html).
```
'use strict';

import React, { Component } from 'react'; 
import { 
	StyleSheet, 
	View,
	Text
} from 'react-native';

import ModalDropdown from 'react-native-modal-dropdown';

var NumberOfColumnsWide	= 10;

class UserDemographicsView extends React.Component {
	constructor(props) {
    	super(props);

    	this.state = {};
    	this.setState = this.setState.bind(this);
    }
	render() {
		return (
			<View style={styles.container} >
				<ModalDropdown options={['option 1', 'option 2']}/>
			</View>
		);
	}
}

const styles = StyleSheet.create({ 
	container: { 
		flex: NumberOfColumnsWide, 
		backgroundColor: '#ff0000',
		flexDirection: 'row',
	}
});

module.exports = UserDemographicsView;
```
![img_0022](https://cloud.githubusercontent.com/assets/1033734/19863141/561eeeb0-9f50-11e6-92a6-6f4c0f396a72.PNG)

**Comment by sohobloo** [comment]
@DrBeak1 
I'm clear now the position of the drop down is related to the 'window' rather than the sheet.
But I'm not sure I can fix it immediately since I can't find a way to judge what container to relate to when I need to calculate the position. And even I know it, I don't know how to calculate the position neither.

**Comment by sohobloo** [comment]
@DrBeak1 
I have an idea to workaround this issue:
Let user to re-calculate the position of the dropdown to cover my given values in mixed `dropdownStyle`

**Comment by sohobloo** [comment]
There is a workaround solution since v0.4.0.
