### ISSUE TITLE
Is it possible to disable option selection ? 

### ISSUE THREAD

**Issue by Kris4an7** [sohobloo/react-native-modal-dropdown#54]
Hello,
Is it possible to disable the options selection ?
I want when I press the button, two options to show and if you click anywhere in that field, instead of picking the option, the ModalDropdown just goes back to the default.

Thank you !

**Comment by sohobloo** [comment]
Some useful info here:
onDropdownWillHide: Trigger when dropdown will hide by touching the button. Return false can cancel the event.

onSelect => (idx, value): Trigger when option row touched with selected index and value. Return false can cancel the event.

https://github.com/sohobloo/react-native-modal-dropdown#methods

**Comment by Kris4an7** [comment]
Thanks !
