### ISSUE TITLE
Button text is an object

### ISSUE THREAD

**Issue by hiepvv** [sohobloo/react-native-modal-dropdown#55]
I have a probem when i use options data is a list of objects, and when i selected an option then button text show an object. How can I get a property of object and show on Button
Example: I want to show name of list people on Button when I selected
![a](https://cloud.githubusercontent.com/assets/19855405/25541687/d236c26e-2c79-11e7-8176-1891dbdf686b.png)

**Comment by eyalabadi98** [comment]
following. How did you solve this?

**Comment by hiepvv** [comment]
hi @eyalabadi98, here is my code
Hope it helps
```
<Dropdown style={styles.dropdown}
  dropdownStyle={styles.dropdownStyle}
  renderRow={this.renderRow.bind(this)}
  options={this.props.listData}
  onSelect={(index, newState) => this.changeState(newState)}>
  <View style={styles.dropdownButton}>
    <Text style={styles.dropdownCurrentText}
      numberOfLines={1}
      ellipsizeMode={'tail'}>
      {this.props.currentState}
    </Text>
    <View style={styles.dropdownIconWrap}>
      <Image style={styles.dropdownIcon}
        source={require('../imgs/down-arrow.png')}
      />
    </View>
  </View>
</Dropdown>

renderRow(rowData, rowID, highlighted) {
    return (
      <TouchableHighlight underlayColor='#36baac'>
        <View style={styles.dropdownRow}>
          <Text style={styles.dropdownText} numberOfLines={1} ellipsizeMode={'tail'}>
            {rowData.name}
          </Text>
        </View>
      </TouchableHighlight>
    )
  }
```
![a](https://user-images.githubusercontent.com/19855405/27939641-7098d74c-62f0-11e7-9f47-ab03203da261.png)

**Comment by hdrabs** [comment]
Hi,

I am having the same issue and not to mention I am a newbie. Can you please provide the code for changeState(newState) function? That would be a real help! Thanks!
