### ISSUE TITLE
dropdownTextStyle    不生效

### ISSUE THREAD

**Issue by XIAOYAYAYAYA** [sohobloo/react-native-modal-dropdown#56]
下拉框内文字样式  属性设定  并没有生效   ，如何解决呢？

**Comment by sohobloo** [comment]
@XIAOYAYAYAYA 能否提供部分代码和您的样式？

**Comment by sohobloo** [comment]
@XIAOYAYAYAYA 并没有`dropdownTextStyle`这个属性可以设置，如果您是要定制选项的文字样式，建议您使用`renderRow`方法来自己生成选项行。

**Comment by pengfeiyan** [comment]
https://github.com/sohobloo/react-native-modal-dropdown/blob/master/example/index.js的第86 行
出现了dropdownTextStyle这个属性

            <ModalDropdown ref={el => this._dropdown_3 = el}
                           style={styles.dropdown_3}
                           options={DEMO_OPTIONS_1}
                           adjustFrame={style => this._dropdown_3_adjustFrame(style)}
                           **dropdownTextStyle={styles.dropdown_3_dropdownTextStyle}**
                           dropdownTextHighlightStyle={styles.dropdown_3_dropdownTextHighlightStyle}
/>

**Comment by sohobloo** [comment]
我检查了一下是有这个属性，那么你设置的style是什么呢？哪些属性没有生效？
源代码的设置是这样的：混合了一些style

```
style={[
           styles.rowText,
           this.props.dropdownTextStyle,
           highlighted && styles.highlightedRowText,
           highlighted && this.props.dropdownTextHighlightStyle
         ]}
```

**Comment by sohobloo** [comment]
@XIAOYAYAYAYA 
您好，这个属性是某个PR提交的，还没正式发布，所以npm下载的不带这个属性，你可以等我发布新版本，应该就在这两天！谢谢！
