### ISSUE TITLE
BUG: alert in a modal is automatically dismissed and causes crash in IOS only.

### ISSUE THREAD

**Issue by parameshwar-ande** [sohobloo/react-native-modal-dropdown#57]
When I open alert in a modal ,alert is automatically dismissed and causing crash in IOS where as it is working fine in ANDROID.

**Comment by sohobloo** [comment]
Duplicate to #22. I thought this is an RN's bug, maybe not...

**Comment by parameshwar-ande** [comment]
Hi sohobloo,
Thanks for responding.
My actual requirement is to have alert when dropdown item selected in modal.But the solution suggested to remove alert statement itself. isn't possible to have alert there?
@sohobloo

**Comment by sohobloo** [comment]
@parameshwar-ande 
Try this:
Set `animated` to false.
Save the values on `onSelect`.
`setTimeout` to alert what you want to after the modal disapeared.

**Comment by parameshwar-ande** [comment]
Thanks @sohobloo 
setTimeout worked for me.
Thanks a lot.
