### ISSUE TITLE
Cannot specify {height:xxx} for dropdownStyle. 不能为dropdownStyle指定高度

### ISSUE THREAD

**Issue by cgwu** [sohobloo/react-native-modal-dropdown#6]
道友，懂中文的是吧？不能为dropdownStyle指定高度，指定后报错，dropdownStyle
dropdownStyle={StyleSheet.flatten([styles.dropdownStyle, {height:64}])}
(197行)这一行代码写错了：

`
let dropdownHeight = (this.props.dropdownStyle && StyleSheet.flatten(this.props.dropdownStyle.height)) ||
StyleSheet.flatten(styles.dropdown).height;
// 应该是: .height)   =>    ).height
let dropdownHeight = (this.props.dropdownStyle && StyleSheet.flatten(this.props.dropdownStyle).height) ||
      StyleSheet.flatten(styles.dropdown).height;
`

**Comment by sohobloo** [comment]
@cgwu 
Great job!

So.... 当然懂

**Comment by SoloRN** [comment]
@sohobloo 既然你懂中文，那我就问个问题吧，如何重置一个Dropdown,让它显示defaultValue？？求指教

**Comment by sohobloo** [comment]
@cgwu 

Fixed in [v0.3.1](https://github.com/sohobloo/react-native-modal-dropdown/releases/tag/v0.3.1)

Thanks again!
