### ISSUE TITLE
textStyle invalid in wrapper mode.

### ISSUE THREAD

**Issue by TheMarsGuy** [sohobloo/react-native-modal-dropdown#60]
Will this be added to the roadmap? `textStyle` doesn't seem to take effect when the component is wrapped.

**Comment by sohobloo** [comment]
@TheMarsGuy 
This is impossible and unnecessary. You can directly give the style to the component you wrapped.

**Comment by TheMarsGuy** [comment]
Is there a way to apply styles to the text in the dropdown? If that is the case, I believe it is through 'textStyle', but the styles doesn't seem to get applied.

**Comment by sohobloo** [comment]
`textStyle` is for the trigger button.
You can use `renderRow` to render your custom option rows then apply with your style just like RN's `ListView`.

**Comment by sohobloo** [comment]
@TheMarsGuy 
Here is the PR #49 
Thanks to @evansiroky 
Will release these days.
