### ISSUE TITLE
_this2._dropdown_6_onSelect is not a function

### ISSUE THREAD

**Issue by GitHubThe** [sohobloo/react-native-modal-dropdown#62]
<ModalDropdown style={styles.dropdown_6}
                                   options={DEMO_OPTIONS_1}
                                   onSelect={(idx, value) => this._dropdown_6_onSelect(idx, value)}/>

   _dropdown_6_onSelect(idx, value) {
        this.setState({
            dropdown_6_icon_heart: !this.state.dropdown_6_icon_heart,
        })
    }

**Comment by sohobloo** [comment]
I can't reproduce.
