### ISSUE TITLE
When nested in scroll view the dropdown will issue error

### ISSUE THREAD

**Issue by opp100** [sohobloo/react-native-modal-dropdown#65]
Thanks for the great plugin,

When I using the dropdown inside a scroll view it will lead the "Attempted to transition from state 'NOT_RESPONDER' to RESPONDER_ACTIVE_LONG_PRESS_IN'," error, 
as the follow picture shows. 

I've using RN 0.44 and test this on iOS. 

How can I solve that?
![simulator screen shot 1 jun 2017 16 04 51](https://cloud.githubusercontent.com/assets/19526135/26666668/7eede918-46e4-11e7-8f34-63af480fbe31.png)

**Comment by sohobloo** [comment]
Strange...
I didn't bind any long press event.
I'll try to reproduce it and look out what's wrong

**Comment by opp100** [comment]
Dear Author,

I think this error might be a react native bug. Sorry for the wrong report. 

Anyway, thanks for you help.

**Comment by rishiankush** [comment]
I am getting this same error. kindly help

**Comment by rishiankush** [comment]
got the solution from here:
https://github.com/facebook/react-native/issues/5823#issuecomment-367581273
