### ISSUE TITLE
Events never fire on manual manipulation

### ISSUE THREAD

**Issue by alburdette619** [sohobloo/react-native-modal-dropdown#66]
It'd be nice to have the option to have `onSelect`, for instance, be called when `select(idx)` is called manually.  Would you be open to a PR with a bool to allow this option?  Defaults would be false.

**Comment by sohobloo** [comment]
Hello @alburdette619 ,
It's by design.
I think you can get all the data and states you maintained at the time you call `onSelect`, with which you can do what you want. If you have any unreachable requirement please let me know and we can figure out if this PR is necessary.

**Comment by alburdette619** [comment]
I think you're correct and this may be extraneous.  I'll close this.
