### ISSUE TITLE
重置一个dropdown

### ISSUE THREAD

**Issue by SoloRN** [sohobloo/react-native-modal-dropdown#7]
dropdown已经选择了其中一个option，如何能够重置这个选择，让它显示defalutValue？？

**Comment by sohobloo** [comment]
@SoloRN 
> dropdown已经选择了其中一个option，如何能够重置这个选择，让它显示defalutValue？？

你可以参考example中的右下角的例子：
1. 获取到dropdown控件的引用：[代码](https://github.com/sohobloo/react-native-modal-dropdown/blob/master/example/index.js#L104)
2.  选择索引为-1的项`select(-1)`：[代码](https://github.com/sohobloo/react-native-modal-dropdown/blob/master/example/index.js#L99)

**Comment by SoloRN** [comment]
@sohobloo thanks, it works, 
另外
1.最好能加上renderSeparatorStyle 
2.component情况下，title不能设置margin（代码307 button）
3.options的TouchableHighlight 没有underlayColor设置

**Comment by sohobloo** [comment]
@SoloRN 

> 1.最好能加上renderSeparatorStyle 
可以的，下个版本加renderSeparator

> 2.component情况下，title不能设置margin（代码307 button）
可以设置`textStyle`的margin：[代码1](https://github.com/sohobloo/react-native-modal-dropdown/blob/master/example/index.js#L54) [代码2](https://github.com/sohobloo/react-native-modal-dropdown/blob/master/example/index.js#L229)

> 3.好意见，我想接下来可以这样设计，如果使用了自定义的renderRow，我就用TouchableWithoutFeedback，不自主改变任何样式，使用者可以自己在renderRow的时候再添加一层TouchableHighlight或者TouchableOpacity来自主控制样式。RN应该支持双层Touchable嵌套吧我猜。
