### ISSUE TITLE
Open dropdown at active option

### ISSUE THREAD

**Issue by RyanMitchellWilson** [sohobloo/react-native-modal-dropdown#70]
Is there a way to show the active option once you open a dropdown? Currently I have a long list inside the dropdown and have it limited to show 5 options. I'm trying to have the dropdown already scrolled to the active option once I open it, is this currently possible?

**Comment by sohobloo** [comment]
It's a little bit difficulty since I didn't expose the scrollView inside this component.

**Comment by sohobloo** [comment]
dup #106

**Comment by bdtren** [comment]
Re-open. 
I recommend using `FlatList` other than  `deprecated-react-native-listview` and give a ways to access to its references. Because `FlatList` have already the `scrollToIndex` function!

**Comment by bdtren** [comment]
Re-open. 
I recommend using `FlatList` other than  `deprecated-react-native-listview` and give a ways to access to its reference. Because `FlatList` have already the `scrollToIndex` function!
