### ISSUE TITLE
Change black color on select

### ISSUE THREAD

**Issue by marina2909** [sohobloo/react-native-modal-dropdown#73]
Is it possible to change default black background colour when I select some option? I have 0.4.4 version and from one of the previous posts I assumed it was fixed but I can't find way how to change it. Tnx!

**Comment by chenyi5266** [comment]
you should write  the renderRow  by yourself , and you can choose TouchableHighlight, TouchableNativeFeedback or TouchableOpacity ....
if  use  TouchableHighlight , you can add underlayColor="lightgray"        like this 

<ModalDropdown 
        ...
	renderRow={this._renderRow.bind(this)}
>

_renderRow() {
                     <TouchableHighlight
	 			underlayColor="lightgray"
	 		>
	 			<View style={styles.dropdownTextStyle}>
	 				<Text style={styles.dropdownTextInner}>{rowData.name}</Text>
	 			</View>
	 		</TouchableHighlight>

}
