### ISSUE TITLE
你好 我有个样式问题 

### ISSUE THREAD

**Issue by QuYunFengg** [sohobloo/react-native-modal-dropdown#74]
![screenshot_2017-07-07-10-45-21-850_com nooshnotif](https://user-images.githubusercontent.com/29081440/27941091-6ba22e30-6301-11e7-8332-953a0938d173.png)
我怎么样可以让下面的modal跟随边框 而不是跟随字出现
就是宽刚好从边框那里出来

**Comment by sohobloo** [comment]
下拉框显示出来的时候位置是经过计算的，位置应该是和按钮对齐的。你是否将控件当做容器，而截图中显示的按钮还有一层父控件，且父控件比按钮宽？
你可以通过`adjustFrame`方法来覆盖计算出来的style并作为返回值即可。

**Comment by QuYunFengg** [comment]
OK了 十分感谢

**Comment by QuYunFengg** [comment]
不好意思朋友 我又发现了一个新问题 不知道可以解决吗 
我使用ios时 点击旁边 我的侧边栏会收回 但是这个modal并不会消失 
![screenshot_2017-07-07-15-33-40-110_com nooshnotif](https://user-images.githubusercontent.com/29081440/27947738-b2295d10-6329-11e7-9b5e-351170e6dcf3.png)

**Comment by sohobloo** [comment]
是否是你的panResponder劫持了事件？

**Comment by sohobloo** [comment]
你可以手动调用dropdown引用的`hide()`方法来隐藏dropdown。

**Comment by QuYunFengg** [comment]
可以 加下QQ 帮我看看吗 因为我用了react-native-drawer组件 我不太清楚该怎么写 隐藏方法  
我的 QQ：510689947

**Comment by sohobloo** [comment]
已加
