### ISSUE TITLE
How to display arrow down icon

### ISSUE THREAD

**Issue by wincychan** [sohobloo/react-native-modal-dropdown#77]
I am using [material icon](https://material.io/icons/) in my project. Is there any way to add custom arrow down icon next to selected value for custom layout? Thanks
![icon arrow down](https://user-images.githubusercontent.com/28753498/28453275-30e17890-6e29-11e7-880b-96ccc9ace51d.png)

**Comment by sohobloo** [comment]
@wincychan 
Use this component as a wrapper then you can render the your custom trigger. (See my example).
You can change the triangle icon display / animation on `onDropdownWillShow` and `onDropdownWillHide` callback if need.

**Comment by wincychan** [comment]
@sohobloo Thanks a lot :)

**Comment by sohobloo** [comment]
@wincychan 
You are welcome.

**Comment by Vasault** [comment]
sorry if this is already closed, but where is the "component" you're talking about?
