### ISSUE TITLE
Get rid of extra space when there are few options 

### ISSUE THREAD

**Issue by clay-morgan** [sohobloo/react-native-modal-dropdown#78]
If you have only a few options, is there a way to get rid of the extra space that appears at the bottom of the options list?

**Comment by sohobloo** [comment]
@clay-morgan 
Maybe you can calculate the dropdown height through the row count and give a height/minHeight/maxHeight style to it.

**Comment by clay-morgan** [comment]
Thanks, seems to have no issues on the emulator I'm using currently
