### ISSUE TITLE
DropDown Dynamic Height

### ISSUE THREAD

**Issue by sujalBandhara** [sohobloo/react-native-modal-dropdown#81]
Is it possible to set height based on data?

**Comment by sohobloo** [comment]
Yes you can calculate and set the height style yourself.

**Comment by MaxInMoon** [comment]
how?

**Comment by wincod75** [comment]
+1

**Comment by MaxLeshchenko** [comment]
+1

**Comment by AfflatusX** [comment]
set dropdownStyle to {height: 'auto'}

**Comment by ardencaliskaner** [comment]
Yes it is possible if  use adjust frame , you should set style.height=-1 also dynamic if want dynamic with set the style.width=-1

Example:

   <ModalDropdown
                        showsVerticalScrollIndicator={false}
                        defaultIndex={0}
                        options={this.state.options}
                        textStyle={styles.dTextStyle}
                        renderRow={this.dropDownRender.bind(this)}
                        dropdownStyle={styles.ddrpFirmStyle}
                        dropdownTextStyle={styles.ddrtTextStyle}
                        onSelect={this.props.onSelect}
                        **adjustFrame={style => this.drpFrame(style)}**
                        onDropdownWillShow={() => {
                            if (this.state.options.length === 0) {
                                this.setState({ modalOpen: true });
                                setTimeout(() => this.setState({ modalOpen: false }), 2000);
                            }
                        }}
/>

 drpFrame(style) {

         style.width = width - 60;
        **style.height = this.state.options.length > 4 ? 200 : - 1;**
        return style;
    }

**Comment by SopoB** [comment]
@AfflatusX after using height:'auto' its going upwards

**Comment by sumitrahate** [comment]
you can set dynamic height using height:array.length multiply 50>400? 400:array.length multiply  50
this will set max height to 400 or else num of array element * 50
