### ISSUE TITLE
ModalDropdown not redrawing if default index changes

### ISSUE THREAD

**Issue by drdavej** [sohobloo/react-native-modal-dropdown#88]
I've been using Modal Dropdown, it has been working very well for me.  But I have one drop-down which sets the 'current month' for a calendar app.  Everything works great if I change the current month using the modal dropdown.  But there is another path for changing the month, and when this path is used, the value changes, the scene re-renders, but Modal Dropdown displays the old month.

I have the following two lines as part of the dropdown:
  defaultIndex={this.state.curMonthIdx}
  defaultValue={this.state.curMonthStr}

As I mentioned, other things in the scene rerender.  The Modal Dropdown displays the old data.  What should I do to cause the correct redraw?

**Comment by sohobloo** [comment]
@drdavej 
the default value can not change dynamic.
Maybe this can help you understand what happened.
https://github.com/sohobloo/react-native-modal-dropdown/issues/43#issuecomment-307299640

**Comment by drdavej** [comment]
OK, was able to track things down.  In my scene's constructor, added this:

constructor()
{...
  this._monthDropdown = null;
...}

In the render, when I am creating the ModalDropdown, I have:

<ModalDropdown
   ...
   ref={el => this._monthDropdown = el}
   ...>

Then in my other routine that can switch the month, I have this:

calendarGoForward()
{...
   this._monthDropdown && this._monthDropdown.select(newVal);
...}

The trick was using the 'ref...' to save a reference to the ModalDropdown, so that later we could call its select method.
