### ISSUE TITLE
Change dropdown selected state programmatically 

### ISSUE THREAD

**Issue by imasif** [sohobloo/react-native-modal-dropdown#89]
Hello, I need to change the dropdowns selected method on another event in my code occurs,
I tried with:
`select={(idx)=> this._dropdown_select(idx).bind(this)}`

 ```
   _dropdown_select(idx){
        return idx;
    }
```

and I'm calling it like this:
`this._dropdown_select(0);`

I think I'm doing something stupid, or missing something, can you help me? @sohobloo

**Comment by sohobloo** [comment]
@imasif 
call the `select(idx)` of the reference of the dropdown on your method.
