### ISSUE TITLE
react native 0.37版本报错   

### ISSUE THREAD

**Issue by alukaka** [sohobloo/react-native-modal-dropdown#9]
找不到updateposition这个方法,
0.3.1已经移出了这个方法  可是我的0.3.1还是提示这个方法没有
谢谢

**Comment by alukaka** [comment]
建议使用0.3.0版本，0.3.1版本无法使用，各位道友请自行选择

**Comment by sohobloo** [comment]
@alukaka 

请问是您之前的代码里有手动调用updatePosition方法吗？如果有可以将调用去掉即可，0.3.0之后的版本不需要手动调用哦。

**Comment by alukaka** [comment]
之前0.3.0版本的时候有写过这个方法，后来删除之后能使用，但是今早更新了react-native到0.37后，也顺便升级至0.3.1，但是报错，然后我又只能使用0.3.0版本

**Comment by sohobloo** [comment]
@alukaka 
谢谢反馈，目前发现之前少删了一行代码，但是我这边没有报错。如果你没有定制dropdown高度的需求的话可以继续使用之前版本。抱歉哦。

**Comment by alukaka** [comment]
哈哈   没事   还要感谢你呢   省去很多事    options  那里 点击准备选择时  好像会有一个空白的  比如我有4个选项  但是却好像出来了5个的位置 这里应该可以优化一下
