### ISSUE TITLE
dropdownStyle borderTopWidth has no effect on android

### ISSUE THREAD

**Issue by uragecz** [sohobloo/react-native-modal-dropdown#91]
Hi, any tips why border(Top/Bottom/Left/Right)Width on dropdownStyle doesn't work?? Normal borderWidth works fine... but when i want to set width to some certain side, it has no effect..

**Comment by sohobloo** [comment]
![image](https://user-images.githubusercontent.com/13310861/36024632-4a897efe-0dcb-11e8-83bd-b74ea4030fba.png)

It's working for me both iOS and Android.
See the example and change the `dropdown_2_dropdown` style into
```js
  dropdown_2_dropdown: {
    width: 150,
    height: 300,
    borderColor: 'red',
    borderWidth: 2,
    borderRadius: 3,
    borderTopWidth: 10
  },
```
